-- 修复数据库表结构

-- 为 attendance_records 表添加缺失的字段
ALTER TABLE attendance_records 
ADD COLUMN IF NOT EXISTS "signTime" TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS "userName" TEXT,
ADD COLUMN IF NOT EXISTS "location" JSONB,
ADD COLUMN IF NOT EXISTS "latitude" NUMERIC,
ADD COLUMN IF NOT EXISTS "longitude" NUMERIC,
ADD COLUMN IF NOT EXISTS "customFields" JSONB,
ADD COLUMN IF NOT EXISTS "attendanceid" BIGINT,
ADD COLUMN IF NOT EXISTS "userid" BIGINT;

-- 为用户表添加可能缺失的字段
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS "username" TEXT,
ADD COLUMN IF NOT EXISTS "name" TEXT,
ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'user',
ADD COLUMN IF NOT EXISTS "phone" TEXT,
ADD COLUMN IF NOT EXISTS "email" TEXT,
ADD COLUMN IF NOT EXISTS "avatar" TEXT,
ADD COLUMN IF NOT EXISTS "groupId" BIGINT,
ADD COLUMN IF NOT EXISTS "createdBy" TEXT;

-- 为签到表添加可能缺失的字段
ALTER TABLE attendances 
ADD COLUMN IF NOT EXISTS "name" TEXT,
ADD COLUMN IF NOT EXISTS "type" TEXT DEFAULT 'normal',
ADD COLUMN IF NOT EXISTS "mode" TEXT DEFAULT 'once',
ADD COLUMN IF NOT EXISTS "startTime" TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS "endTime" TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS "locationName" TEXT,
ADD COLUMN IF NOT EXISTS "latitude" NUMERIC,
ADD COLUMN IF NOT EXISTS "longitude" NUMERIC,
ADD COLUMN IF NOT EXISTS "rangeMeters" INTEGER DEFAULT 200,
ADD COLUMN IF NOT EXISTS "targetType" TEXT DEFAULT 'all',
ADD COLUMN IF NOT EXISTS "targetGroups" JSONB,
ADD COLUMN IF NOT EXISTS "targetMembers" JSONB,
ADD COLUMN IF NOT EXISTS "customFields" JSONB,
ADD COLUMN IF NOT EXISTS "isRepeat" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "repeatType" TEXT DEFAULT 'daily',
ADD COLUMN IF NOT EXISTS "repeatDays" JSONB,
ADD COLUMN IF NOT EXISTS "dailyStartTime" TEXT,
ADD COLUMN IF NOT EXISTS "dailyEndTime" TEXT,
ADD COLUMN IF NOT EXISTS "createdBy" TEXT;

-- 为通知表添加可能缺失的字段
ALTER TABLE notifications 
ADD COLUMN IF NOT EXISTS "title" TEXT,
ADD COLUMN IF NOT EXISTS "message" TEXT,
ADD COLUMN IF NOT EXISTS "type" TEXT,
ADD COLUMN IF NOT EXISTS "senderId" BIGINT,
ADD COLUMN IF NOT EXISTS "receiverId" BIGINT,
ADD COLUMN IF NOT EXISTS "isPrivate" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "parentId" BIGINT,
ADD COLUMN IF NOT EXISTS "read" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "relatedId" BIGINT;

-- 为学习记录表添加缺失的 plan_id 列
ALTER TABLE study_records 
ADD COLUMN IF NOT EXISTS "plan_id" UUID REFERENCES study_plans(id) ON DELETE SET NULL;

-- 为学习记录表创建索引（如果不存在）
CREATE INDEX IF NOT EXISTS idx_study_records_plan_id ON study_records(plan_id);

-- 为学习计划表添加缺失的列
ALTER TABLE study_plans 
ADD COLUMN IF NOT EXISTS "priority" TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
ADD COLUMN IF NOT EXISTS "reminder_enabled" BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS "reminder_time" TIME;

-- 为学习记录表添加 enhanced-database.sql 中的其他列
ALTER TABLE study_records 
ADD COLUMN IF NOT EXISTS "topic" TEXT,
ADD COLUMN IF NOT EXISTS "duration_minutes" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "study_type" TEXT DEFAULT 'review',
ADD COLUMN IF NOT EXISTS "focus_score" INTEGER DEFAULT 0 CHECK (focus_score BETWEEN 0 AND 100),
ADD COLUMN IF NOT EXISTS "productivity_score" INTEGER DEFAULT 0 CHECK (productivity_score BETWEEN 0 AND 100),
ADD COLUMN IF NOT EXISTS "completed_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
